#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config \
    mouse_follows_focus         off           \
    focus_follows_mouse         off           \
    window_placement            second_child  \
    window_topmost              off           \
    window_opacity              off           \
    window_animation_duration   0.0           \
    window_opacity_duration     1.0           \
    window_shadow               on            \
    insert_feedback_color       0xaad75f5f    \
    active_window_opacity       1.0           \
    normal_window_opacity       1.0           \
    split_ratio                 0.50          \
    auto_balance                on            \
    mouse_modifier              fn            \
    mouse_action1               move          \
    mouse_action2               resize        \
    layout                      bsp           \
    top_padding                 4             \
    bottom_padding              4             \
    left_padding                4             \
    right_padding               4             \
    window_gap                  6             \
    window_border               off

yabai -m config window_animation_duration 0.1

# 160	23	164
# 182 78 185


# add 30 padding to the top and bottom of all spaces regardless of the display it belongs to
# yabai -m config external_bar all:34:0

yabai -m config --space 1 layout float

## setting or information
yabai -m rule --add app="飞书*"          manage=off
yabai -m rule --add app="Lark*"          manage=off
yabai -m rule --add app="Sentinel*"      manage=off
yabai -m rule --add app="微信*"          manage=off
yabai -m rule --add app="系统设置"       manage=off layer=above
yabai -m rule --add app="Seal"           manage=off layer=above
yabai -m rule --add app="ClashX"         manage=off layer=above
yabai -m rule --add app="Stretchly"      manage=off layer=above
yabai -m rule --add app="词典"           manage=off layer=above
yabai -m rule --add app="计算器"         manage=off layer=above
yabai -m rule --add app="Python"         manage=off layer=above

# signals:
# yabai -m signal --add event=window_destroyed       action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# signals for yabar:
# yabar is a xbar plugin for yabai, more abort yabar: https://github.com/yangtau/dotfiles/tree/main/yabai/yabar
REFRESH_YABAR="open -gj 'xbar://app.xbarapp.com/refreshPlugin?path=yabar.1d.cgo'"
# yabai -m signal --add event=space_changed        action="$REFRESH_YABAR"
# yabai -m signal --add event=display_added        action="$REFRESH_YABAR"
# yabai -m signal --add event=display_removed      action="$REFRESH_YABAR"
# yabai -m signal --add event=display_changed      action="$REFRESH_YABAR"
# yabai -m signal --add event=display_moved        action="$REFRESH_YABAR"
# yabai -m signal --add event=mission_control_exit action="$REFRESH_YABAR"

echo "yabai configuration loaded.."
