#!/bin/bash

TMPBG=/tmp/screen.png
scrot $TMPBG && convert $TMPBG -scale 5% -scale 2000%  $TMPBG


i3lock \
  -i $TMPBG \
  --insidecolor=0000001c \
  --ringcolor=0000003e   \
  --linecolor=00000000   \
  --keyhlcolor=ffffff80   \
  --ringvercolor=ffffff00 \
  --separatorcolor=22222260 \
  --insidevercolor=ffffff1c \
  --verifcolor=333333ee \
  --insidewrongcolor=ff000009\
  --ringwrongcolor=ff000055 \
  --wrongcolor=ff0000ff  \
  --bshlcolor=ff000055 \
  -k --datestr="%d, %m, %Y" \
  --timestr="%H:%M"  \
  --wrongtext='wrong!' \
  --timecolor=333333ee \
  --datecolor=333333ee \
  --layoutcolor=ffffff00 \
  --ring-width=7.0  \
  --radius=100 \
  --time-font="Fira Code" \
  --date-font="Fira Code" \
  --timesize=50 \
  --datesize=16

rm $TMPBG

